name: Godot Debug Build
on:
  push:
    branches:    
      - 'develop'

env:
  GODOT_VERSION: 4.3
  EXPORT_NAME: SSGMDX3
  PROJECT_PATH: ./

jobs:
  export-windows:
    name: Windows Debug Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      
      - name: Cache Import Assets
        uses: actions/cache@v4
        with:
          path: .godot/imported/
          key: import_assets

      - name: Build
        run: |
          mkdir -v -p build/windows
          cd $PROJECT_PATH
          godot --headless --verbose --editor --quit
          godot --headless --verbose --export-debug "win_x86_64" ./build/windows/$EXPORT_NAME.exe
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SSGMDX3 (Debug)
          path: build/windows