name: Export Build
on:
  push:
    branches:
      - develop
      - main

env:
  GODOT_VERSION: 4.3
  EXPORT_NAME: SSGMDX3
  PROJECT_PATH: ./

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      
      - name: Cache Import Assets
        uses: actions/cache@v4
        with:
          path: .godot/imported/
          key: import_assets

      - name: Windows Release Build
        if: github.ref == 'refs/heads/main'
        run: |
          mkdir -v -p build/windows
          cd $PROJECT_PATH
          godot --headless --verbose --editor --quit
          godot --headless --verbose --export-release "win_x86_64" ./build/windows/$EXPORT_NAME.exe

      - name: Windows Debug Build
        if: github.ref == 'refs/heads/develop'
        run: |
          mkdir -v -p build/windows
          cd $PROJECT_PATH
          godot --headless --verbose --editor --quit
          godot --headless --verbose --export-debug "win_x86_64" ./build/windows/$EXPORT_NAME_DEBUG.exe
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SSGMDX3
          path: build/windows